version: 2

models:
  - name: stg_raw__stock
    columns:
      - name: product_id
        description: unique combination of model color size
        tests:
          - not_null
          - unique
      - name: color_name
        description: color of the product in full
        tests:
          - no_color