version: 2

sources:
  - name: raw
    schema: raw_data_circle
    tables:
      - name: sales
        identifier: raw_cc_sales
        tests:
          - unique:
              column_name: "(product_id || '_' || date_date)"
      - name: stock
        identifier: raw_cc_stock
      - name: parcel
        identifier: raw_cc_parcel
        columns:
          - name: Parcel_id
            tests:
              - unique
          - name: Transporter
            tests:
              - not_null
              - accepted_values:
                  values: ['colissimo', 'ups']
